#!/usr/bin/env bash

## Install ansible
sudo apt-add-repository -y ppa:ansible/ansible
sudo apt-get update -y
sudo apt-get install -y curl git software-properties-common ansible
sudo ansible-galaxy collection install community.general

## pull ansible
# sudo ansible-pull -U https://github.com/johnmarco123/ansible.git
