#!/usr/bin/env bash

## Install ansible
sudo apt-add-repository -y ppa:ansible/ansible
sudo apt-get update -y
sudo apt-get install -y curl git software-properties-common ansible
sudo ansible-galaxy collection install community.general

## Install all the things
ansible-playbook --ask-vault-pass -K local.yml
