- hosts: localhost
  tasks:
    - name: Starting core-setup tasks
      import_tasks: tasks/core-setup.yml
      tags: 
        - core

    - name: Starting node tasks
      import_tasks: tasks/node.yml
      tags: 
        - install
        - node
        - js

