- name: Install nodejs and npm
  become: true
  apt:
    name: ["nodejs", "npm"]

- name: Install nvm
  become: true
  ansible.builtin.shell: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
    
