- name: Install productivity packages (tmux, i3, xclip, tldr, gh, fzf, ripgrep)
  become: true
  apt:
    name: ["tmux", "i3", "xclip", "tldr", "gh", "fzf", "ripgrep" ]

- name: Install productivity packages 2 (peek, shutter)
  become: true
  apt:
    name: ["peek", "shutter"]
